### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by kllelndhlm** [CasimirLaine/data-compressor-python#3]
Reviewed code retrieved on 18 August 2022 at 19:30

The project shares the same subject as my own, Huffman and Lempel-Ziw data compression, although the style the code is written in differs from what I'm accustomed to (mine is a little less refined). However it is accessible and easy to follow even to someone not so advanced in the field. The quality of naming and commenting benefits to this greatly.

The project seems to be proceeding well, with most aspects underway or finished. Unfortunately I was unable run the program following the instructions given in the README file. When given command 'python setup.py', the response was: 
```bash
File "setup.py", line 8
    f'python -m venv venv',
                         ^
SyntaxError: invalid syntax'
```
after which 'python main.py' responded:
```bash
  File "main.py", line 6
    path_prefix = f'{root_path}{os.sep}'
                                       ^
SyntaxError: invalid syntax
```
Perhaps the problem was at my side, but there could be a more For Dummies type of manual. The test commands worked and a coverage file was created.

Good work!

**Comment by CasimirLaine** [comment]
Thank you for the feedback! Could you please check that you are running Python version 3.6+.
As it seems that the issue is with f-strings (f'string'). They were added as a language feature in 3.6. 
https://stackoverflow.com/questions/55182209/f-string-invalid-syntax-in-python-3-5

I recommend you install 3.10 as this project is built with it.
